/*
 dhtmlxScheduler.Net v.3.2.0 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
Scheduler.plugin(function(e){e.config.icons_select=["icon_details","icon_delete"],e.config.details_on_create=!0,e.config.show_quick_info=!0,e.xy.menu_width=0,e.attachEvent("onClick",function(t){return e.showQuickInfo(t),!0}),function(){for(var t=["onEmptyClick","onViewChange","onLightbox","onBeforeEventDelete","onBeforeDrag"],n=function(){return e._hideQuickInfo(),!0},a=0;a<t.length;a++)e.attachEvent(t[a],n)}(),e.templates.quick_info_title=function(e,t,n){return n.text.substr(0,50)},e.templates.quick_info_content=function(e,t,n){return n.details||n.text
},e.templates.quick_info_date=function(t,n,a){return e.isOneDayEvent(a)?e.templates.day_date(t,n,a)+" "+e.templates.event_header(t,n,a):e.templates.week_date(t,n,a)},e.showQuickInfo=function(e){if(e!=this._quick_info_box_id&&this.config.show_quick_info){this.hideQuickInfo(!0);var t=this._get_event_counter_part(e);t&&(this._quick_info_box=this._init_quick_info(t),this._fill_quick_data(e),this._show_quick_info(t))}},e._hideQuickInfo=function(){e.hideQuickInfo()},e.hideQuickInfo=function(t){var n=this._quick_info_box;
if(this._quick_info_box_id=0,n&&n.parentNode){var a=n._offsetWidth;if(e.config.quick_info_detached)return n.parentNode.removeChild(n);"auto"==n.style.right?n.style.left=-a+"px":n.style.right=-a+"px",t&&n.parentNode.removeChild(n)}},dhtmlxEvent(window,"keydown",function(t){27==t.keyCode&&e.hideQuickInfo()}),e._show_quick_info=function(t){var n=e._quick_info_box;e._obj.appendChild(n);var a=n.offsetWidth,i=n.offsetHeight;e.config.quick_info_detached?(n.style.left=t.left-t.dx*(a-t.width)+"px",n.style.top=t.top-(t.dy?i:-t.height)+"px"):(n.style.top=this.xy.scale_height+this.xy.nav_height+20+"px",1==t.dx?(n.style.right="auto",n.style.left=-a+"px",setTimeout(function(){n.style.left="-10px"
},1)):(n.style.left="auto",n.style.right=-a+"px",setTimeout(function(){n.style.right="-10px"},1)),n.className=n.className.replace("dhx_qi_left","").replace("dhx_qi_right","")+" dhx_qi_"+(1==t?"left":"right"))},e.attachEvent("onTemplatesReady",function(){if(e.hideQuickInfo(),this._quick_info_box){var t=this._quick_info_box;t.parentNode&&t.parentNode.removeChild(t),this._quick_info_box=null}}),e._quick_info_onscroll_handler=function(){e.hideQuickInfo()},e._init_quick_info=function(){if(!this._quick_info_box){var t=e.xy,n=this._quick_info_box=document.createElement("div");
n.className="dhx_cal_quick_info",e.$testmode&&(n.className+=" dhx_no_animate");var a='<div class="dhx_cal_qi_title" style="height:'+t.quick_info_title+'px"><div class="dhx_cal_qi_tcontent"></div><div  class="dhx_cal_qi_tdate"></div></div><div class="dhx_cal_qi_content"></div>';a+='<div class="dhx_cal_qi_controls" style="height:'+t.quick_info_buttons+'px">';for(var i=e.config.icons_select,r=0;r<i.length;r++)a+='<div class="dhx_qi_big_icon '+i[r]+'" title="'+e.locale.labels[i[r]]+"\"><div class='dhx_menu_icon "+i[r]+"'></div><div>"+e.locale.labels[i[r]]+"</div></div>";
a+="</div>",n.innerHTML=a,dhtmlxEvent(n,"click",function(t){t=t||event,e._qi_button_click(t.target||t.srcElement)}),e.config.quick_info_detached&&(e._detachDomEvent(e._els.dhx_cal_data[0],"scroll",e._quick_info_onscroll_handler),dhtmlxEvent(e._els.dhx_cal_data[0],"scroll",e._quick_info_onscroll_handler))}return this._quick_info_box},e._qi_button_click=function(t){var n=e._quick_info_box;if(t&&t!=n){var a=t.className;if(-1!=a.indexOf("_icon")){var i=e._quick_info_box_id;e._click.buttons[a.split(" ")[1].replace("icon_","")](i)
}else e._qi_button_click(t.parentNode)}},e._get_event_counter_part=function(t){for(var n=e.getRenderedEvent(t),a=0,i=0,r=n;r&&r!=e._obj;)a+=r.offsetLeft,i+=r.offsetTop-r.scrollTop,r=r.offsetParent;if(r){var s=a+n.offsetWidth/2>e._x/2?1:0,d=i+n.offsetHeight/2>e._y/2?1:0;return{left:a,top:i,dx:s,dy:d,width:n.offsetWidth,height:n.offsetHeight}}return 0},e._fill_quick_data=function(t){var n=e.getEvent(t),a=e._quick_info_box;e._quick_info_box_id=t;var i=a.firstChild.firstChild;i.innerHTML=e.templates.quick_info_title(n.start_date,n.end_date,n);
var r=i.nextSibling;r.innerHTML=e.templates.quick_info_date(n.start_date,n.end_date,n);var s=a.firstChild.nextSibling;s.innerHTML=e.templates.quick_info_content(n.start_date,n.end_date,n)}});