/*
 dhtmlxScheduler.Net v.3.2.0 Professional Evaluation

This software is covered by DHTMLX Evaluation License. Contact sales@dhtmlx.com to get Commercial or Enterprise license. Usage without proper license is prohibited.

(c) Dinamenta, UAB.
*/
scheduler.config.multisection=!0,scheduler.config.multisection_shift_all=!0,scheduler.config.section_delemiter=",",scheduler.attachEvent("onSchedulerReady",function(){var e=scheduler._update_unit_section;scheduler._update_unit_section=function(t){return scheduler._update_sections(t,e)};var t=scheduler._update_timeline_section;scheduler._update_timeline_section=function(e){return scheduler._update_sections(e,t)},scheduler.isMultisectionEvent=function(e){if(e&&this._get_multisection_view()){var t=this._get_event_sections(e);
return t.length>1}return!1},scheduler._get_event_sections=function(e){var t=this._get_section_property(),a=e[t]||"";return this._parse_event_sections(a)},scheduler._parse_event_sections=function(e){return e instanceof Array?e:e.toString().split(scheduler.config.section_delemiter)},scheduler._register_copies_array=function(e){for(var t=0;t<e.length;t++)this._register_copy(e[t])},scheduler._register_copy=function(e){this._multisection_copies[e.id]||(this._multisection_copies[e.id]={});var t=e[this._get_section_property()],a=this._multisection_copies[e.id];
a[t]||(a[t]=e)},scheduler._get_copied_event=function(e,t){if(!this._multisection_copies[e])return null;if(this._multisection_copies[e][t])return this._multisection_copies[e][t];var a=this._multisection_copies[e];if(scheduler._drag_event&&scheduler._drag_event._orig_section&&a[scheduler._drag_event._orig_section])return a[scheduler._drag_event._orig_section];var i=1/0,n=null;for(var s in a)a[s]._sorder<i&&(n=a[s],i=a[s]._sorder);return n},scheduler._clear_copied_events=function(){this._multisection_copies={}
},scheduler._clear_copied_events(),scheduler._split_events=function(e){var t=[],a=this._get_multisection_view(),i=this._get_section_property();if(a)for(var n=0;n<e.length;n++){var s=this._get_event_sections(e[n]);if(s.length>1){for(var r=0;r<s.length;r++)if("undefined"!=typeof a.order[s[r]]){var d=this._lame_copy({},e[n]);d[i]=s[r],t.push(d)}}else t.push(e[n])}else t=e;return t},scheduler._get_multisection_view=function(){return this.config.multisection?scheduler._get_section_view():!1};var a=scheduler.get_visible_events;
scheduler.get_visible_events=function(){this._clear_copied_events();var e=a.apply(this,arguments);if(this._get_multisection_view()){e=this._split_events(e);for(var t=0;t<e.length;t++)this.is_visible_events(e[t])||(e.splice(t,1),t--);this._register_copies_array(e)}return e},scheduler._rendered_events={};var i=scheduler.render_view_data;scheduler.render_view_data=function(e,t){return this._get_multisection_view()&&e&&(e=this._split_events(e),this._restore_render_flags(e)),i.apply(this,[e,t])},scheduler._restore_render_flags=function(e){for(var t=this._get_section_property(),a=0;a<e.length;a++){var i=e[a],n=scheduler._get_copied_event(i.id,i[t]);
if(n)for(var s in n)0===s.indexOf("_")&&(i[s]=n[s])}},scheduler._update_sections=function(e,t){var a=e.view,i=e.event,n=e.pos;if(scheduler.isMultisectionEvent(i)){if(scheduler._drag_event._orig_section||(scheduler._drag_event._orig_section=n.section),scheduler._drag_event._orig_section!=n.section){var s=a.order[n.section]-a.order[scheduler._drag_event._orig_section];if(s){var r=this._get_event_sections(i),d=[],o=!0;if(scheduler.config.multisection_shift_all)for(var _=0;_<r.length;_++){var l=scheduler._shift_sections(a,r[_],s);
if(null===l){d=r,o=!1;break}d[_]=l}else for(var _=0;_<r.length;_++){if(r[_]==n.section){d=r,o=!1;break}if(r[_]==scheduler._drag_event._orig_section){var l=scheduler._shift_sections(a,r[_],s);if(null===l){d=r,o=!1;break}d[_]=l}else d[_]=r[_]}o&&(scheduler._drag_event._orig_section=n.section),i[scheduler._get_section_property()]=d.join(",")}}}else t.apply(scheduler,[e])},scheduler._shift_sections=function(e,t,a){for(var i in e.order)if(e.order[i]-e.order[t]==a)return i;return null};var n=scheduler._get_blocked_zones;
scheduler._get_blocked_zones=function(e,t,a,i,s){if(t&&this.config.multisection){t=this._parse_event_sections(t);for(var r=[],d=0;d<t.length;d++)r=r.concat(n.apply(this,[e,t[d],a,i,s]));return r}return n.apply(this,arguments)};var s=scheduler._check_sections_collision;scheduler._check_sections_collision=function(e,t){if(this.config.multisection&&this._get_section_view()){e=this._split_events([e]),t=this._split_events([t]);for(var a=!1,i=0,n=e.length;n>i&&!a;i++)for(var r=0,d=t.length;d>r;r++)if(s.apply(this,[e[i],t[r]])){a=!0;
break}return a}return s.apply(this,arguments)}});